# Generated by Django 6.1.1 on 2026-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('research_notes', models.TextField(blank=True)),
                ('draft', models.TextField(blank=True)),
                ('review_feedback', models.TextField(blank=True)),
                ('review_status', models.CharField(blank=True, max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('final_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
